### ISSUE TITLE
Não consigo logar na conta o programa fecha

### ISSUE THREAD

**Issue by DLangkamer** [AmanoTeam/Ara#68]
![image](https://github.com/AmanoTeam/Ara/assets/145389691/e918be89-ac04-441c-8286-59a904ecf886)
Ao abrir o ARA, normalmente não consigo logar, simplesmente fecha. Excluí o usuário do appdata, mas continua o problema, vi que possui um issue pedindo para abrir via powershell
Tentei executar via powersheel, mas o aparece o seguinte erro, poderia me ajudar
PS: o usuário e senha estão corretos

**Comment by Kartatz** [comment]
Entre em contato comigo via [e-mail](mailto:luissilvaferreira@protonmail.com).

**Comment by DLangkamer** [comment]
> Entre em contato comigo via [e-mail](mailto:luissilvaferreira@protonmail.com).

Pronto!

**Comment by Kartatz** [comment]
Duplicata da #55. Não é um problema do Ara.
