### ISSUE TITLE
Sugestão: Baixar Todos Cursos no Menu

### ISSUE THREAD

**Issue by rafaelmattos** [AmanoTeam/Ara#72]
Primeiramente, parabéns pelo projeto. Salvou meu investimento, e se eu conhecesse antes teria me poupado muito mais.
Minha sugestão era ter no Menu a opção Baixar Todos Cursos. E ao finalizar o download de um curso retornar ao Menu.
Como fechou o programa não sabia dizer foi um crash ou apenas terminou de baixar.
Estou usando no estratégia militares. Tenho 15 cursos lá.

**Comment by Kartatz** [comment]
> Minha sugestão era ter no Menu a opção Baixar Todos Cursos

Você pode baixar múltiplos cursos de uma só vez especificando um intervalo de início e fim.

Por exemplo:

* Se você possui 15 cursos e quer baixar todos eles, digite `1-15` e pressione Enter.

* Se você quer baixar os três primeiros que aparecem na listagem, digite `1-3`.

E assim por diante.

> Como fechou o programa não sabia dizer foi um crash ou apenas terminou de baixar.

O recomendado é que você sempre abra manualmente o programa através do PowerShell, pois desse modo a janela do terminal não irá fechar por conta própria em caso de erros ou coisas do gênero.

**Comment by rafaelmattos** [comment]
blz! obgdo!
