### ISSUE TITLE
Data Science Academy

### ISSUE THREAD

**Issue by rafaelmattos** [AmanoTeam/Ara#73]
Há previsão do programa dar suporte à Plataforma da Data Science Academy? (datascienceacademy.com.br)

**Comment by Kartatz** [comment]
Eu não tenho conta neste site. Se você estiver disposto e me emprestar a sua, posso dar uma olhada.

**Comment by rafaelmattos** [comment]
Eu não tenho mais cursos pagos nesse site. Se eu tivesse conhecido antes,
com certeza emprestaria. Porém eles disponibilizam cursos gratuitos na
mesma plataforma, acredito que por ser a mesma conta, tvz seja possível.

Em sex., 13 de out. de 2023 às 11:52, Kartatz ***@***.***>
escreveu:

**Comment by Kartatz** [comment]
Você pode fazer isso via [e-mail](mailto:luissilvaferreira@protonmail.com).
