### ISSUE TITLE
Erro ao baixar curso do Hotmart

### ISSUE THREAD

**Issue by RealLuscas** [AmanoTeam/Ara#74]
Boa tarde, descobri hoje sobre a sua aplicação, e ao tentar utilizar para baixar o curso encontro o erro descrito na imagem. Como seria possível solucionar este problema?
![2023-10-18](https://github.com/AmanoTeam/Ara/assets/148380733/020f9038-9398-44d7-8ba8-96541d4bca51)

**Comment by Kartatz** [comment]
Você tem outros cursos nessa conta? Se sim, o mesmo problema ocorre quando você tenta baixá-los?

**Comment by RealLuscas** [comment]
Tenho um único outro curso, está até expirado já, só contém uns arquivos de texto nele. Mas ao tentar baixar, não houve esse mesmo erro, acredito ter funcionado corretamente.
![2023-10-18 (1)](https://github.com/AmanoTeam/Ara/assets/148380733/d88e5fd5-86d0-4b4c-92ac-1dfcd49c2c5d)

**Comment by Kartatz** [comment]
Entre em contato comigo via [e-mail](mailto:luissilvaferreira@protonmail.com) para que possamos discutir melhor sobre esse problema.
