### ISSUE TITLE
Programa fechando ao tentar realizar download do hotmart

### ISSUE THREAD

**Issue by tbaragao** [AmanoTeam/Ara#75]
Estou tentando realizar o download de um curso que adquiri do hotmart, o program faz login, reconhece a listagem, consigo navegar pela lista (tenho mais de 15 cursos) usando as setas do teclado, o programa até reconhece a pasta e cria a pasta localmente, mas fecha finaliza quando tentar realizar o download do primeiro video.

**Comment by Kartatz** [comment]
O mínimo que se exige ao reportar um problema é enviar uma imagem (captura de tela) do erro que é exibido no momento em que você está usando o programa.

Sem isso não posso fazer nada.

**Comment by tbaragao** [comment]
Estava rodando ele no cmd, ai nao consegui ver a mensagem de erro. Abri no powershell agora consegui. Esta dando 403:

![image](https://github.com/AmanoTeam/Ara/assets/10468125/38a8e749-ecea-4454-abef-a60b6e1c1a5a)

**Comment by Kartatz** [comment]
Esse problema já foi corrigido. Aguarde o lançamento da próxima versão que ocorrerá daqui há 3 semanas ou baixe a versão de pré-lançamento disponível aqui.

**Comment by tbaragao** [comment]
Muito obrigado pelo retorno e pelo desenvolvimento da tool

**Comment by waltheraa** [comment]
Como que baixa essa versão de pre lançamento?

**Comment by Leozinhubatatinha** [comment]
> O mínimo que se exige ao relatar um problema é enviar uma imagem (captura de tela) do erro que é exibida no momento em que você está usando o programa.
> 
> Sem isso não posso fazer nada.

o meu tbm está assim, quando vai baixar, o tool fecha e aparece apenas uma pasta vazia
