### ISSUE TITLE
- Ocorreu uma falha inesperada ao tentar conectar com o servidor HTTP: The requested URL returned error: 403

### ISSUE THREAD

**Issue by hostsistemas** [AmanoTeam/Ara#77]
- Ocorreu uma falha inesperada ao tentar conectar com o servidor HTTP: The requested URL returned error: 403

este erro aconteceu ao tentar baixar pela hotmart

**Comment by Kartatz** [comment]
Leia as issues já criadas antes de abrir uma nova.
